/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'on-secondary-fixed': '#111d23',
        'primary-fixed': '#72fe8f',
        'on-background': '#191c1c',
        error: '#ba1a1a',
        'on-surface-variant': '#3c4a3c',
        'on-tertiary-fixed': '#410002',
        'surface-container-highest': '#e1e3e2',
        'primary-fixed-dim': '#53e076',
        'surface-dim': '#d8dada',
        'on-error-container': '#93000a',
        'surface-bright': '#f8faf9',
        'on-secondary-fixed-variant': '#3c494f',
        'on-primary-fixed-variant': '#005320',
        surface: '#f8faf9',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ffdad6',
        'secondary-fixed-dim': '#bbc8d0',
        tertiary: '#9d4139',
        'inverse-on-surface': '#eff1f0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f3',
        'error-container': '#ffdad6',
        'outline-variant': '#bbcbb8',
        'tertiary-container': '#ff8d81',
        'inverse-primary': '#53e076',
        'secondary-fixed': '#d7e4ec',
        'on-primary-container': '#004c1d',
        'on-primary': '#ffffff',
        'surface-variant': '#e1e3e2',
        secondary: '#546067',
        background: '#f8faf9',
        'primary-container': '#32c65f',
        'on-surface': '#191c1c',
        'on-tertiary-container': '#76251f',
        'surface-container': '#eceeed',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2e3131',
        'on-primary-fixed': '#002108',
        'on-tertiary-fixed-variant': '#7e2a24',
        'on-secondary-container': '#5a666d',
        'tertiary-fixed-dim': '#ffb4ab',
        outline: '#6c7b6a',
        primary: '#006e2d',
        'surface-container-high': '#e6e8e7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      backgroundImage: {
        'primary-gradient': 'linear-gradient(135deg, #006e2d 0%, #32c65f 100%)',
      },
      boxShadow: {
        card: '0 12px 32px -4px rgba(25,28,28,0.06)',
        float: '0 20px 48px -8px rgba(25,28,28,0.10)',
      },
    },
  },
  plugins: [],
};
